name: softpatterns
channels:
  - conda-forge
  - soumith
dependencies:
  - python==3.6.3
  - mkl==2017.0.3
  - numpy==1.13.1
  - pyyaml==3.12
  - pytorch==0.2.0
  - magma-cuda80
  - ipython==6.2.0
  - pip:
    - tensorboardx==0.8
